### ISSUE TITLE
Invalid multiaddr error on windows

### ISSUE THREAD

**Issue by OwlWilderness** [valory-xyz/trader-quickstart#34]
Wondering if this would be appropriate in the quickstart readme or somewhere else.  I can also create an issue on the open aea repo - I was looking into a bit but realized I need to do a bit more learning first and wanted to document the work around. Thanks.

#### Error: _Invalid multiaddr_
Running the init prepends an incorrect value to the ipfs_repo on windows 
```
autonomy init --reset --author valory --remote --ipfs --ipfs-node "/dns/registry.autonolas.tech/tcp/443/https"
```

```
[2023-09-28 20:00:29,303][INFO] (protocol, open_aea/signing:1.0.0) not found locally, downloading...
Error: Invalid multiaddr string provided, valid format: /{dns,dns4,dns6,ip4}/<host>/tcp/<port>/protocol. Provided: C:/Program Files/Git/dns/registry.autonolas.tech/tcp/443/https
```
Navigate to your users .aea folder and open the cli.config.yamal file
```
 C:\Users\<user_name>\.aea\cli_config.yaml
```
Verify ipfs_node value = /dns/registry.autonolas.tech/tcp/443/https
```
author: valory
registry_config:
  default: remote
  settings:
    local:
      default_packages_path: null
    remote:
      default: ipfs
      http:
        auth_token: null
        registry_api_url: null
      ipfs:
        ipfs_node: /dns/registry.autonolas.tech/tcp/443/https
```
